### ISSUE TITLE
Beginner reCaptcha issue

### ISSUE THREAD

**Issue by mycodehobby** [jonmbake/bootstrap3-contact-form#27]
I believe I followed all the step in readme file but I get this issue error:invalid-input-secret
Check it out here:  http://mycodehobby.com/contact_test.html

**Comment by mycodehobby** [comment]
I believe my issue exists in the htaccess file, would like a way to avoid using htaccess all together for these recaptcha variables.

**Comment by jonmbake** [comment]
See my comment in the other issue. If you are having issues, email me (jonmbake@gmail.com) and we can work through them.
