### ISSUE TITLE
Question: How to use bootstrap validator

### ISSUE THREAD

**Issue by Simonn-** [jonmbake/bootstrap3-contact-form#8]
I would prefer to use bootstrap validator. How can I integrate it instead of using the one you built? 

https://1000hz.github.io/bootstrap-validator/

**Comment by jonmbake** [comment]
There is currently no way to swap out the validator.  Let me try a quick refactoring tonight and see if I can get something working.  I'll get back to you.

**Comment by jonmbake** [comment]
I added a bit of support for Bootstrap Validator: https://github.com/jonmbake/bootstrap3-contact-form/commit/3670a878ced845ffb0283942f5a34bb4a3fa95b5.  You will probably also want to remove `display: none` from the `help-blocks`.  Let me know how things work out.

**Comment by Simonn-** [comment]
Thanks you @jonmbake
